### ISSUE TITLE
Units for Live consumption

### ISSUE THREAD

**Issue by aksvenk** [mindmelting/hass-powerpal#10]
I'm thinking this should be reported in kW and not kWh since it is a measure of instantaneous power.

**Comment by mindmelting** [comment]
Hey - thanks for the feedback. What comes back from the API is not real time instant measurement - it's watt usage over the course of a minute. This then gets converted into kWh - hope that makes (some) sense!

I've taken the kWh outputs from this plugin along with energy price integration from Amber - and it's almost exactly my bill price - so it's pretty accurate.

**Comment by aksvenk** [comment]
Thanks for your reply, that makes sense. The powerpal app confused me a bit as the instantaneous power is shown in Watts(W) on the 'energy clock'.

[Looking at the API](https://readings.powerpal.net/documentation) I see data is actually coming through in watt-hours(Wh)

**Comment by mindmelting** [comment]
Ah nice - they have published details on the api response now!
