### ISSUE TITLE
The link to Documentation is incorrect

### ISSUE THREAD

**Issue by gurrier** [mindmelting/hass-powerpal#13]
## Configuration

```yaml

Add your logs here.

```

## Describe the bug

The link has a typo in it, missing final "p" in powerpal

https://github.com/mindmelting/hass-poweral

## Debug log

```text

Add your logs here.

```

**Comment by mindmelting** [comment]
This has been fixed : https://github.com/mindmelting/hass-powerpal/pull/11 just not released a new version for this

**Comment by mindmelting** [comment]
Release v0.2.2
