### ISSUE TITLE
Broken images when README.md is viewed in HACS 

### ISSUE THREAD

**Issue by mercurytoxic** [mindmelting/hass-powerpal#19]
Hi, thanks for an awesome integration. There are a couple images broken when you view the README.md from HACS.

![image](https://user-images.githubusercontent.com/739809/221330394-8dfcdfdc-58ef-48fd-9d3d-e4274118c9d0.png)

the links to images the in the README.md are not absolute file paths to github but local file paths.

"[sensorimg]: sensor.png"
"[energyimg]: energy.png"

**Comment by mindmelting** [comment]
Ah thanks! Let me approve PR (although need to fix the build)
