### ISSUE TITLE
Error: Credentials are incorrect

### ISSUE THREAD

**Issue by HappySl0th** [mindmelting/hass-powerpal#26]
I retrieved the API key using https://forfuncsake.github.io/post/2021/08/owning-my-own-powerpal-data/ and it is in the format of XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX and I got the device ID from the Powerpal app 0000XXXX. When entering these values into the integrations, I get "Credentials are incorrect". Is there a way to check the credentials? I already have a tablet running Powerpal to get the values into the app.

**Comment by mindmelting** [comment]
Hey @HappySl0th - that sounds like the right values you are using - unlikely to be the issue but can you check everything is lowercase?

**Comment by HappySl0th** [comment]
I tried it with lowercase and still showing the same error. Is the API key and token the same?

**Comment by mindmelting** [comment]
They are yes...

**Comment by HappySl0th** [comment]
Using WeekendWarrior1 python retrieval script worked. The API key is different from forfuncsake.
