### ISSUE TITLE
Advice on integration - App and HA totals are out by 1kWh

### ISSUE THREAD

**Issue by tgcowell** [mindmelting/hass-powerpal#3]
Hi,

Firstly thanks for creating this integration, I have been able to get it working within my setup which is great. I am however wanting some advice on how often it communications with 'readings' as it doesn't seem to be 'live' and the total power consumption is out by nearly 1kWh (compared with the app)

Is there anything I am missed or need to adjust? or is this expected as it's not providing accurate real time data?

**Comment by mindmelting** [comment]
Hey @tgcowell - it makes a call to the `readings` API once per minute.

The `readings` API returns a value `last_reading_watt_hours` which is used to determine the value you see in the `Powerpal Live Consumption` sensor (not quite live, but the nearest we have access to)

I believe this value gets sent to the Powerpal servers once per minute by the App you have connected to the Powerpal device - however there are times when running in the background or not open (unless connected to power) - that it may not update straight away, and send a batch over every 15 minutes (I think - not confirmed!)

Can you check if the Energy Dashboard shows a correct daily energy consumption using the `Powerpal Total Consumption` which should be quite accurate?

I'll take a more detailed look into the "Live" values soon - although I don't think can do too much beyond the existing implementation...

**Comment by tgcowell** [comment]
Hi @mindmelting 

Apologies this is working as per your suggested times above, I for some reason was thinking it was 'real time' like the app. I'm closing this as realistically your comment above really answers my question.

Thanks again really appreciate the integration now to creating some automation
