### ISSUE TITLE
not showing in HA

### ISSUE THREAD

**Issue by stackner** [mindmelting/hass-powerpal#4]
ive installed via HACS. it shows in HACS but even after reboot it does not show in HA as an integration to install.....
![pal 1](https://user-images.githubusercontent.com/33416783/137609712-8b102fe6-5830-4907-a821-cd9e80a61ec6.png)
![pal 2](https://user-images.githubusercontent.com/33416783/137609713-23adfcc6-fe04-400c-a4b9-718eabb3dd54.png)

**Comment by mindmelting** [comment]
@stackner I just tested in a fresh install of HA and HACS - and seems to show up as expected when adding as an integration. Are you able to see it being loaded (similar to below) in the logs?
```bash
2021-10-17 11:17:58 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration powerpal which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
```

**Comment by mindmelting** [comment]
Going to close this issue for now - happy to help debug your HA setup if needed.

**Comment by starryalley** [comment]
I think this is due to browser cache? This happened to me just now but I then used the ipad HA app and Powerpal just pops up after search.
