### ISSUE TITLE
Any way to add data from powerpal server prior to the integration installation?

### ISSUE THREAD

**Issue by botts7** [mindmelting/hass-powerpal#8]
Hi There,

Thanks so much for this integration.

Is there a way to load pervious data to HA, prior to having installed the component?

Obviously I can download the CSV file, but how do Add it to the newly recorded data in HA?

Thanks in advance

**Comment by mindmelting** [comment]
Hi @botts7 - Even though historic information can be used from the API - I don't think there is a way to import historic entity states into Home Assistant (I looked into this a while ago) - however if there is I will gladly implement!

**Comment by mindmelting** [comment]
Will close this for now!
